#!/bin/bash

# Exit immediately if a command fails
set -e

# Validate the script is being run in the correct context
if [ ! -e ./.stage0_template ]; then
    echo "Error: This script must be run from the root of the repo. Ensure the repo is an unprocessed Stage0 template repository."
    exit 1
fi

# Setup the environment
LOG_LEVEL="${LOG_LEVEL:-INFO}"
SERVICE_NAME="${SERVICE_NAME:-partner}"
SPECIFICATIONS_PATH="${SERVICE_NAME:-/specifications}"

# Run the container
echo "Merging Templates..."
docker run --rm \
    -v "$(pwd):/repo" \
    -v "$SPECIFICATIONS_PATH:/specifications" \
    -e LOG_LEVEL=$LOG_LEVEL \
    -e SERVICE_NAME=$SERVICE_NAME \
    ghcr.io/agile-learning-institute/stage0-generator:latest

echo "Done, thank you for flying with stage0."
